# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/osx'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'Guigna-RubyMotion'
  app.version = "0.0.1"
  app.short_version = "Pre-Alpha"
  app.identifier = "name.soranzio.guido.Guigna-RubyMotion"
  app.icon = "guigna.icns"
  app.frameworks += ['WebKit', 'ScriptingBridge']
  app.delegate_class = 'GuignaAppDelegate'
  app.info_plist['NSMainNibFile'] = 'MainMenu'
  
  # workaround as for http://hipbyte.myjetbrains.com/youtrack/issue/RM-240
  # to avoid "ld: warning: PIE disabled. Absolute addressing (perhaps -mdynamic-no-pic)
  # not allowed in code signed PIE, ..." 
  app.archs['MacOSX'] = ['x86_64']
  app.codesign_for_release = false
  app.codesign_certificate = ""
end
